### ISSUE TITLE
Version number went down

### ISSUE THREAD

**Issue by cbargren** [rvdkooy/react-testutils-additions#11]
Generally, when you bump a version number, `0.15.0` would be seen as later than `0.2.0`, when using [semantic versioning](http://semver.org/), which React adheres to. From Spec (2), `Each element MUST increase numerically`.  If you want to bump the version in a more clearly breaking way, perhaps using 1.0.0 or 0.20.0 would be a better choice.

**Comment by rvdkooy** [comment]
You're absolutely right!
I mixed up the version numbers with another package

Will bump the latest version to 0.16.0 (what I actually wanted to do)

**Comment by cbargren** [comment]
Cool, thanks!
