### ISSUE TITLE
Can I find by id to see if a component does not exist?

### ISSUE THREAD

**Issue by goopscoop** [rvdkooy/react-testutils-additions#12]
I have a component that hides child components from users. When I test this, I'm using find by Id, but rather than returning false or something like that, it's erroring out. Is there a good way around this?

**Comment by rvdkooy** [comment]
I think we need a scryRenderedDOMComponentsWithId helper for that.
this method won't throw, it just returns an empty array if nothing is found.

or you can do this?

TestUtils.find(component, '#myid');

**Comment by rvdkooy** [comment]
@goopscoop can I close this issue?

**Comment by goopscoop** [comment]
Yes, thanks.
