### ISSUE TITLE
React 15 compatibility?

### ISSUE THREAD

**Issue by gbhasha** [rvdkooy/react-testutils-additions#16]
After updating to React version 15.0.0, I am getting following warnings when I do npm install 

npm WARN EPEERINVALID react-testutils-additions@0.16.1 requires a peer of react@0.14.x but none was installed.
npm WARN EPEERINVALID react-testutils-additions@0.16.1 requires a peer of react-addons-test-utils@0.14.x but none was installed.
npm WARN EPEERINVALID react-testutils-additions@0.16.1 requires a peer of react-dom@0.14.x but none was installed.

**Comment by rvdkooy** [comment]
just upgraded it to version 15 to align the versionnumbering with react.

thanks!

Gr, R
