### ISSUE TITLE
Attribute Selectors

### ISSUE THREAD

**Issue by davidkpiano** [rvdkooy/react-testutils-additions#18]
Is it possible to do this?

``` js
TestUtils.find(page, '[data-target^="starts-with-"]')
```

or any other attribute selectors such as `foo^=bar`, `foo*=bar`, `foo$=bar`, etc.

**Comment by rvdkooy** [comment]
I'm not sure:

I use sizzle as the css selector engine so if they support it, react-testutils-additions should support it.
Maybe you can check their documentation for some hints:
https://github.com/jquery/sizzle
