### ISSUE TITLE
Again 'findRenderedDOMComponentWithId()' should be more useful.

### ISSUE THREAD

**Issue by aravindsurya77** [rvdkooy/react-testutils-additions#22]
I believe the main motto of adding this method to the react-testUtils-Additions is to facilitate to search an element based on its 'id' and since the id is unique, the scry version of this method might not be useful. I agree with this. But, there are some scenarios where this method is not useful, for which a developer might want to use. For example in my case, clicking on a button redirects my app to the home page. There is an element with a unique id in the home page, which is not present in the page where currently I am. Now I want to assert my button click as a success based on two assertions.
1. findRenderedDOMComponentWithId() before the click -- where the element is not present
2. findRenderedDOMComponentWithId() after the click -- where the element is present.

Problem is, the test blows up right away at the first method call, since, the rendered DOM doesn't have an element with the id I am passing.

So my suggestion would be, instead of throwing an exception, since the 'find' methods only return one value. Why don't you guys change the return type to a boolean?

I believe this makes the testing a lot easier and flexible.

**Comment by rvdkooy** [comment]
My intention is to make the API compatible and as consistent as possible with `ReactTestUtils`.
All find methods in `ReactTestUtils` throw: https://facebook.github.io/react/docs/test-utils.html#findrendereddomcomponentwithclass, so findRenderedDOMComponentWithId will also throw.

react-testutils-additions gives you other helpers to accomplish your goal like:

``` javascript
testUtilsAdditions.find(component, "#myid"); // returns an empty array if none are found

testUtilsAdditions.findOne(component, "#myid"); // If more or none is found, this will throw!
```

I hope this was usefull

With kind regards,

R
