### ISSUE TITLE
Works with React 16, Babel 7, and latest jsdom?

### ISSUE THREAD

**Issue by dschinkel** [rvdkooy/react-testutils-additions#28]
It's been about 3 years since I used this lib.  I don't use it but was just firing it up and playing with it a little but of course now I'm using React 16, Babel v7, and the latest jsdom which is a bit diff in terms of syntax now but you still are setting up the same globals though for window and document.  

Does it still work with React 16 and latest?  Is this even supported anymore? For some odd reason I get a `null` back when I call `renderIntoDocument()` and yes jsdom (latest) is loaded into memory.

I'm just rendering a very simple functional component:
```
import React from 'react'

const MyFunctionalComopnent = () => <div data-test="header" />

export default MyFunctionalComopnent;
```

Looking at the latest in this repo, you're using React 16, but you're still using babel v6.  I don't see though where you're using jsdom, doesn't look like you are.

If this project is no longer supported can you please officially depreciate it

**Comment by rvdkooy** [comment]
@dschinkel I haven't done much on this lately. but it's not deprecated for me.
Functional components should be rendered by using: `renderIntoTestContainer` because they need to be wrapped (I noticed that I never documented this)

Can you check this?

Sorry for the late response

**Comment by rvdkooy** [comment]
Tested with latest versions of all packages and still works, closing this issue

**Comment by dschinkel** [comment]
Sorry I got busy.  Thanks for the reply.  I'll try out what you said eventually.  Good to know.
