### ISSUE TITLE
TestUtils.renderIntoDocument does not pass props to component

### ISSUE THREAD

**Issue by smith-kyle** [rvdkooy/react-testutils-additions#6]
I think this was caused by the recent extension of the `renderIntoDocument` function

**Comment by rvdkooy** [comment]
you are right, I will fix this ASAP

R

**Comment by smith-kyle** [comment]
Thanks :+1:
To avoid any possible problems with React updates, you might consider not directly overriding anything in TestUtils. Maybe give your override  slightly different name?

**Comment by rvdkooy** [comment]
Yeah, that's probably a better idea.
I was thinking of "RenderIntoTestContainer", or just:  "render"

**Comment by rvdkooy** [comment]
Can send me a code sample?
I'm trying this with the latest version:

```
var Component = React.createClass({
    render: function(){ 
        return (<div>{ this.props.foo }</div>); 
    }
});

var RenderedComponent = TestUtils.renderIntoDocument(<Component foo="foo" />);
```

it prints out:

```
<div id="testcontainer" data-reactid=".0"><div data-reactid=".0.0">foo</div></div
```

R

**Comment by smith-kyle** [comment]
``` javascript
this.component = TestUtils.renderIntoDocument(
  <Component
    myProp='foo' />
);
var props = this.component.props; // props is an empty object
```

In your example above, `this.props` is inside of the Component definition, so there's no problem finding the props. I just realized that the new `renderIntoDocument` is changing the return value from the Component to the testcontainer. Hence in the above snippet, I couldn't find my props and I couldn't figure out why.

This wouldn't be an issue if the testcontainer got the same props as the contained Component; but ideally, an overridden method should never change which object gets returned. Renaming to `renderIntoTestContainer` sounds like a good solution.

**Comment by rvdkooy** [comment]
version 0.15.0 is available on npm

renderIntoDocument is the original ReactTestutils helper, instead use renderIntoTestContainer for the updateProps helper.

Thanks
R.
