### ISSUE TITLE
unMountComponent rename

### ISSUE THREAD

**Issue by smith-kyle** [rvdkooy/react-testutils-additions#8]
It's really a small detail but to keep consistency with React's capitalization `unMountFromDocument` should be renamed to `unmountFromDocument` with a lower case m.

**Comment by rvdkooy** [comment]
I will do it with the next release.

The old function should first give a warning that it will be deprecated in future releases

so it will take at least 2 releases before it is gone.

Thanks

R

**Comment by rvdkooy** [comment]
this is fixed in the latest version
